export const CITIES_LIST = [
    { "value": "london", "label": "London" },
    { "value": "manchester", "label": "Manchester" },
    { "value": "birmingham", "label": "Birmingham" },
    { "value": "leeds", "label": "Leeds" },
    { "value": "glasgow", "label": "Glasgow" },
    { "value": "liverpool", "label": "Liverpool" },
    { "value": "newcastle", "label": "Newcastle" },
    { "value": "sheffield", "label": "Sheffield" },
    { "value": "bristol", "label": "Bristol" },
    { "value": "edinburgh", "label": "Edinburgh" },
    { "value": "cardiff", "label": "Cardiff" },
    { "value": "nottingham", "label": "Nottingham" },
    { "value": "coventry", "label": "Coventry" },
    { "value": "sunderland", "label": "Sunderland" },
    { "value": "brighton", "label": "Brighton" },
    { "value": "hull", "label": "Hull" },
    { "value": "leicester", "label": "Leicester" },
    { "value": "portsmouth", "label": "Portsmouth" },
    { "value": "york", "label": "York" },
    { "value": "oxford", "label": "Oxford" },
    { "value": "cambridge", "label": "Cambridge" },
    { "value": "aberdeen", "label": "Aberdeen" },
    { "value": "derby", "label": "Derby" },
    { "value": "plymouth", "label": "Plymouth" },
    { "value": "southampton", "label": "Southampton" },
    { "value": "stoke", "label": "Stoke-on-Trent" },
    { "value": "norwich", "label": "Norwich" },
    { "value": "wolverhampton", "label": "Wolverhampton" },
    { "value": "preston", "label": "Preston" },
    { "value": "swansea", "label": "Swansea" },
    { "value": "exeter", "label": "Exeter" },
    { "value": "lincoln", "label": "Lincoln" },
    { "value": "dundee", "label": "Dundee" },
    { "value": "chester", "label": "Chester" },
    { "value": "wakefield", "label": "Wakefield" },
    { "value": "durham", "label": "Durham" },
    { "value": "bath", "label": "Bath" },
    { "value": "newport", "label": "Newport" },
    { "value": "new_york", "label": "New York" },
    { "value": "los_angeles", "label": "Los Angeles" },
    { "value": "chicago", "label": "Chicago" },
    { "value": "houston", "label": "Houston" },
    { "value": "phoenix", "label": "Phoenix" },
    { "value": "philadelphia", "label": "Philadelphia" },
    { "value": "san_antonio", "label": "San Antonio" },
    { "value": "san_diego", "label": "San Diego" },
    { "value": "dallas", "label": "Dallas" },
    { "value": "austin", "label": "Austin" },
    { "value": "jacksonville", "label": "Jacksonville" },
    { "value": "san_francisco", "label": "San Francisco" },
    { "value": "miami", "label": "Miami" },
    { "value": "atlanta", "label": "Atlanta" },
    { "value": "boston", "label": "Boston" },
    { "value": "seattle", "label": "Seattle" },
    { "value": "denver", "label": "Denver" },
    { "value": "san_jose", "label": "San Jose" },
    { "value": "detroit", "label": "Detroit" },
    { "value": "nashville", "label": "Nashville" },
    { "value": "memphis", "label": "Memphis" },
    { "value": "baltimore", "label": "Baltimore" },
    { "value": "louisville", "label": "Louisville" },
    { "value": "milwaukee", "label": "Milwaukee" },
    { "value": "portland", "label": "Portland" },
    { "value": "las_vegas", "label": "Las Vegas" },
    { "value": "albuquerque", "label": "Albuquerque" },
    { "value": "tucson", "label": "Tucson" },
    { "value": "fresno", "label": "Fresno" },
    { "value": "sacramento", "label": "Sacramento" }
];